In [7]:
# to be ignored when copying in the main file
import pandas as pd
import requests
import json
import time

In [13]:
#reading excel
wikidata = pd.read_excel('Wikipedia_ready_xl.xlsx')  
#creating dataframe with wiki data
df =pd.DataFrame(wikidata)

In [15]:
df

    Rank                                  Page  Views in millions
0      1                          Harry Potter                 77
1      2                  Fifty Shades of Grey                 49
2      3                A Song of Ice and Fire                 48
3      4                      The Hunger Games                 46
4      5                                 Bible                 34
5      6                      The Great Gatsby                 32
6      7                 The Lord of the Rings                 30
7      8                  Nineteen Eighty-Four                 28
8      9                     A Game of Thrones                 27
9     10                            Kama Sutra                 25
10    11                 To Kill a Mockingbird                 24
11    12      Alice's Adventures in Wonderland                 23
12    12                        Les Misérables                 23
13    14                   The Handmaid's Tale                 22
14    14                              Watchmen                 22
15    16                   The Winds of Winter                 21
16    17                   Pride and Prejudice                 20
17    17  Harry Potter and the Deathly Hallows                 20
18    17       The Girl with the Dragon Tattoo                 20
19    17                The Catcher in the Rye                 20
20    21                               Inferno                 19
21    22                                    It                 18
22    22                                Lolita                 18
23    22                          Frankenstein                 18
24    25                            The Hobbit                 17
25    25                                   Sex                 17
26    25                            Code Geass                 17
27    25            The Picture of Dorian Gray                 17
28    25                           Animal Farm                 17
29    30                               Odyssey                 16
30    30                           Don Quixote                 16
31    30                       Of Mice and Men                 16
32    30                       Brave New World                 16
33    30                               Dracula                 16